# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = app/database/migrations

# template used to generate migration file names; The default version is suitable for most cases.
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file as well as the filename.
# timezone =

# max length of characters to clone to principal. If omitted, default is 40.
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be imported from sys.path
# prepend_syspath = false

# version path separator; default is os.pathsep
# version_path_separator = :

# set to 'true' to search for newer versions in subdirectories
# recursive_version_check = false

# log config file; default is alembic.ini
# log_config = alembic.ini

# sqlalchemy.url is typically configured in env.py dynamically from config settings

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# after generating a new revision file.
# See Alembic documentation for config details.

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
