"""add fields to report table

Revision ID: 0bb5e924ad0c
Revises: cd807a0341ef
Create Date: 2026-07-04 20:55:03.023525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb5e924ad0c'
down_revision: Union[str, Sequence[str], None] = 'cd807a0341ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('grade', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('recommendations', sa.JSON(), nullable=False))
    op.add_column('reports', sa.Column('statistics', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'statistics')
    op.drop_column('reports', 'recommendations')
    op.drop_column('reports', 'grade')
    op.drop_column('reports', 'summary')
    # ### end Alembic commands ###
