"""add_relational_foreign_keys

Revision ID: f66500b955f7
Revises: 
Create Date: 2026-07-04 11:53:11.986234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66500b955f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('scan_db_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_reports_scan_db_id'), 'reports', ['scan_db_id'], unique=True)
    op.create_foreign_key(None, 'reports', 'scans', ['scan_db_id'], ['id'])
    op.add_column('scan_history', sa.Column('scan_db_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_scan_history_scan_db_id'), 'scan_history', ['scan_db_id'], unique=False)
    op.create_foreign_key(None, 'scan_history', 'scans', ['scan_db_id'], ['id'])
    op.add_column('scans', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'scans', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scans', type_='foreignkey')
    op.drop_column('scans', 'user_id')
    op.drop_constraint(None, 'scan_history', type_='foreignkey')
    op.drop_index(op.f('ix_scan_history_scan_db_id'), table_name='scan_history')
    op.drop_column('scan_history', 'scan_db_id')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_scan_db_id'), table_name='reports')
    op.drop_column('reports', 'scan_db_id')
    # ### end Alembic commands ###
