from datetime import datetime, timezone
from app.models.scan import Scan
from app.models.report import Report

class MarkdownReportGenerator:
    """
    Markdown generator class for technical report exports.
    """

    @staticmethod
    def generate(scan: Scan, report: Report) -> str:
        """
        Generates a GitHub-flavored Markdown report.
        """
        scan_date_str = scan.created_at.strftime("%Y-%m-%d %H:%M:%S UTC")
        generated_date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        stats = report.statistics or {}
        critical_count = stats.get("critical", 0)
        high_count = stats.get("high", 0)
        medium_count = stats.get("medium", 0)
        low_count = stats.get("low", 0)
        info_count = stats.get("informational", 0)
        total_vulns = len(scan.vulnerabilities)

        # Markdown layout
        md = f"""# AI Security Audit Report

**Target URL:** {scan.target}  
**Scan ID:** {scan.scan_id}  
**Scan Date:** {scan_date_str}  
**Status:** {scan.status.capitalize()}  

---

# Executive Summary

{report.summary}

---

# Risk Score

* **Assessed Risk Score:** {report.risk_score}/100  
* **Security Grade:** {report.grade}  

---

# Statistics

| Metric | Count |
| :--- | :--- |
| **Total Scanned** | {total_vulns} |
| **Critical** | {critical_count} |
| **High** | {high_count} |
| **Medium** | {medium_count} |
| **Low** | {low_count} |
| **Informational** | {info_count} |

---

# Vulnerabilities

"""

        if scan.vulnerabilities:
            md += "| Severity | Title | Description | Recommendation |\n"
            md += "| :--- | :--- | :--- | :--- |\n"
            for vuln in scan.vulnerabilities:
                sev_label = vuln.severity.upper()
                # Clean any pipe characters inside text to prevent table breaking
                title_clean = vuln.title.replace("|", "\\|")
                desc_clean = vuln.description.replace("|", "\\|").replace("\n", " ")
                rec_clean = vuln.recommendation.replace("|", "\\|").replace("\n", " ")
                md += f"| **{sev_label}** | {title_clean} | {desc_clean} | {rec_clean} |\n"
        else:
            md += "*No vulnerabilities were identified during this security scan.*\n"

        md += "\n---\n\n# Recommendations\n\n"
        if report.recommendations:
            for rec in report.recommendations:
                md += f"* {rec}\n"
        else:
            md += "*No immediate action items recommended.*\n"

        md += f"\n---\n*Generated by AI Security Auditor Engine at {generated_date_str}*"
        return md

